version: '3.8'

services:
  backend:
    image: talknet-server
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/talknet
      - /usr/src/talknet/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongodb
    networks:
      - talknet-internal
  
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/data/db
    networks:
      - talknet-internal

networks:
  talknet-internal:

volumes:
  data:
